[package]
name = "cube-club-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.3", default-features = false, features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
