[default]

[release]
address = "0.0.0.0"
port = 80

[default.databases.cube_club]
url = "cube_club.db"

[default.oauth.google]
provider = "Google"
redirect_uri = "http://localhost:8000/auth/google"

[release.oauth.google]
redirect_uri = "https://cc.mje10.win/auth/google"